Homework #2
Kate-Semenova/automation-python-course pull request #1
Opened 2022-10-24 12:46 UTC by Kate-Semenova

2022-10-24 14:20 UTC, Kate-Semenova commented on lecture2/hw1.py
> +            major = key
I`ve just realized that if we found item >= len(inp) // 2 it is already major element and we don`t need to continue comparing.
I will think of how to refactor this

2022-10-24 15:23 UTC, alpakhomov requested changes
В целом тесты проходят, но первое задание на самом деле проще чем кажется. Есть много способов его решить. Вот подход в "лоб":
- создаем частотный словарь, где ключ это элемент, а значение это сколько раз он встречался. Для этого нужно один раз в цикле пройтись по списку
- дальше нам нужно из этого словаря вернуть ключи, у которых минимальное и максимальное значение. Можно еще раз пройти циклом по словарю, а можно воспользоваться функциями min и max

Есть и другие варианты решения, через те же min и max, через Counter из модуля collections.

Объявление переменных вне функции (major, minor) здесь точно не нужно. Это "чистая" функция - приняла на вход список, вернула кортеж с двумя элементами.

2022-10-27 15:48 UTC, alpakhomov approved these changes
Все ок, принято. Оставил коммент для ознакомления

2022-10-27 15:48 UTC, alpakhomov commented on lecture2/hw1.py
> +    return max(my_dictionary), min(my_dictionary)
Это решение почти правильное. На самом деле тесты проходят из-за того, что там недостаточно тест кейсов, это моя ошибка. 
Если добавить кейс (2, 2, 2, 3, 3) то правильным решением будет (2, 3), а текущее решение вернет (3, 2).
Это можно исправить почти ничего не меняя. Функции max и min опционально принимают параметр key - функцию для определения как именно сравнивать параметры.
Нам нужно сравнение по значению, а сейчас оно происходит по ключу. Но у словаря уже есть функция get, которая возвращает значение.
В итоге можно сделать так:
```py
max(my_dict, key=my_dict.get)
```

2022-10-27 16:22 UTC, Kate-Semenova commented on lecture2/hw1.py
> +    return max(my_dictionary), min(my_dictionary)
Я честно не посмотрела даже как работает мин и макс :) Спасибо, исправлю и засквошу в один комит, надеюсь добьём тогда)

2022-10-28 10:18 UTC, merged